/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ComplaintCategory = IDL.Variant({
  'disciplineRules' : IDL.Null,
  'professorsAcademics' : IDL.Null,
  'administration' : IDL.Null,
  'raggingSafety' : IDL.Null,
  'hostelFacilities' : IDL.Null,
  'foodServices' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Principal = IDL.Principal;
export const SuperAdminBootstrapResult = IDL.Record({
  'principal' : Principal,
  'role' : UserRole,
  'message' : IDL.Text,
  'isAdmin' : IDL.Bool,
});
export const ComplaintStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'submitted' : IDL.Null,
  'underReview' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Complaint = IDL.Record({
  'id' : IDL.Nat,
  'status' : ComplaintStatus,
  'creator' : Principal,
  'urgencyLevel' : IDL.Text,
  'hidden' : IDL.Bool,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : ComplaintCategory,
  'proof' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const CallerInfo = IDL.Record({
  'principal' : Principal,
  'role' : UserRole,
});
export const SolutionUpdate = IDL.Record({
  'id' : IDL.Nat,
  'relatedComplaints' : IDL.Vec(IDL.Nat),
  'title' : IDL.Text,
  'relatedCategories' : IDL.Vec(ComplaintCategory),
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBannedWord' : IDL.Func([IDL.Text], [], []),
  'addSolution' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat), IDL.Vec(ComplaintCategory)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bootstrapSuperAdmin' : IDL.Func([], [SuperAdminBootstrapResult], []),
  'debugGetCallerPrincipal' : IDL.Func([], [Principal], ['query']),
  'deleteComplaint' : IDL.Func([IDL.Nat], [], []),
  'filterComplaintsByCategory' : IDL.Func(
      [ComplaintCategory],
      [IDL.Vec(Complaint)],
      ['query'],
    ),
  'filterComplaintsByStatus' : IDL.Func(
      [ComplaintStatus],
      [IDL.Vec(Complaint)],
      ['query'],
    ),
  'getAdminAllowlist' : IDL.Func(
      [],
      [
        IDL.Record({
          'callerRole' : UserRole,
          'adminPrincipals' : IDL.Vec(Principal),
          'initialAdminPresent' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getAdminAllowlistDebugInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'callerRole' : UserRole,
          'isInitialAdminStillAdmin' : IDL.Bool,
          'isCallerAdmin' : IDL.Bool,
          'initialAdminPrincipal' : Principal,
          'callerPrincipal' : Principal,
        }),
      ],
      ['query'],
    ),
  'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComplaint' : IDL.Func([IDL.Nat], [IDL.Opt(Complaint)], ['query']),
  'getCurrentUserPrincipal' : IDL.Func([], [CallerInfo], ['query']),
  'getPublicComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getSolutions' : IDL.Func([], [IDL.Vec(SolutionUpdate)], ['query']),
  'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
  'hideComplaint' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchComplaints' : IDL.Func([IDL.Text], [IDL.Vec(Complaint)], ['query']),
  'submitComplaint' : IDL.Func(
      [ComplaintCategory, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'updateComplaintStatus' : IDL.Func([IDL.Nat, ComplaintStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ComplaintCategory = IDL.Variant({
    'disciplineRules' : IDL.Null,
    'professorsAcademics' : IDL.Null,
    'administration' : IDL.Null,
    'raggingSafety' : IDL.Null,
    'hostelFacilities' : IDL.Null,
    'foodServices' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Principal = IDL.Principal;
  const SuperAdminBootstrapResult = IDL.Record({
    'principal' : Principal,
    'role' : UserRole,
    'message' : IDL.Text,
    'isAdmin' : IDL.Bool,
  });
  const ComplaintStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'submitted' : IDL.Null,
    'underReview' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Complaint = IDL.Record({
    'id' : IDL.Nat,
    'status' : ComplaintStatus,
    'creator' : Principal,
    'urgencyLevel' : IDL.Text,
    'hidden' : IDL.Bool,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : ComplaintCategory,
    'proof' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const CallerInfo = IDL.Record({ 'principal' : Principal, 'role' : UserRole });
  const SolutionUpdate = IDL.Record({
    'id' : IDL.Nat,
    'relatedComplaints' : IDL.Vec(IDL.Nat),
    'title' : IDL.Text,
    'relatedCategories' : IDL.Vec(ComplaintCategory),
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBannedWord' : IDL.Func([IDL.Text], [], []),
    'addSolution' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat), IDL.Vec(ComplaintCategory)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bootstrapSuperAdmin' : IDL.Func([], [SuperAdminBootstrapResult], []),
    'debugGetCallerPrincipal' : IDL.Func([], [Principal], ['query']),
    'deleteComplaint' : IDL.Func([IDL.Nat], [], []),
    'filterComplaintsByCategory' : IDL.Func(
        [ComplaintCategory],
        [IDL.Vec(Complaint)],
        ['query'],
      ),
    'filterComplaintsByStatus' : IDL.Func(
        [ComplaintStatus],
        [IDL.Vec(Complaint)],
        ['query'],
      ),
    'getAdminAllowlist' : IDL.Func(
        [],
        [
          IDL.Record({
            'callerRole' : UserRole,
            'adminPrincipals' : IDL.Vec(Principal),
            'initialAdminPresent' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getAdminAllowlistDebugInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'callerRole' : UserRole,
            'isInitialAdminStillAdmin' : IDL.Bool,
            'isCallerAdmin' : IDL.Bool,
            'initialAdminPrincipal' : Principal,
            'callerPrincipal' : Principal,
          }),
        ],
        ['query'],
      ),
    'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComplaint' : IDL.Func([IDL.Nat], [IDL.Opt(Complaint)], ['query']),
    'getCurrentUserPrincipal' : IDL.Func([], [CallerInfo], ['query']),
    'getPublicComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getSolutions' : IDL.Func([], [IDL.Vec(SolutionUpdate)], ['query']),
    'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
    'hideComplaint' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchComplaints' : IDL.Func([IDL.Text], [IDL.Vec(Complaint)], ['query']),
    'submitComplaint' : IDL.Func(
        [ComplaintCategory, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'updateComplaintStatus' : IDL.Func([IDL.Nat, ComplaintStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };