/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CallerInfo { 'principal' : Principal, 'role' : UserRole }
export interface Complaint {
  'id' : bigint,
  'status' : ComplaintStatus,
  'creator' : Principal,
  'urgencyLevel' : string,
  'hidden' : boolean,
  'description' : string,
  'timestamp' : bigint,
  'category' : ComplaintCategory,
  'proof' : [] | [ExternalBlob],
}
export type ComplaintCategory = { 'disciplineRules' : null } |
  { 'professorsAcademics' : null } |
  { 'administration' : null } |
  { 'raggingSafety' : null } |
  { 'hostelFacilities' : null } |
  { 'foodServices' : null };
export type ComplaintStatus = { 'resolved' : null } |
  { 'submitted' : null } |
  { 'underReview' : null } |
  { 'inProgress' : null };
export type ExternalBlob = Uint8Array;
export type Principal = Principal;
export interface SolutionUpdate {
  'id' : bigint,
  'relatedComplaints' : Array<bigint>,
  'title' : string,
  'relatedCategories' : Array<ComplaintCategory>,
  'description' : string,
  'timestamp' : bigint,
}
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBannedWord' : ActorMethod<[string], undefined>,
  'addSolution' : ActorMethod<
    [string, string, Array<bigint>, Array<ComplaintCategory>],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'debugGetCallerPrincipal' : ActorMethod<[], Principal>,
  'deleteComplaint' : ActorMethod<[bigint], undefined>,
  'filterComplaintsByCategory' : ActorMethod<
    [ComplaintCategory],
    Array<Complaint>
  >,
  'filterComplaintsByStatus' : ActorMethod<[ComplaintStatus], Array<Complaint>>,
  'getAdminAllowlist' : ActorMethod<
    [],
    {
      'callerRole' : UserRole,
      'adminPrincipals' : Array<Principal>,
      'initialAdminPresent' : boolean,
    }
  >,
  'getAdminAllowlistDebugInfo' : ActorMethod<
    [],
    {
      'callerRole' : UserRole,
      'isInitialAdminStillAdmin' : boolean,
      'isCallerAdmin' : boolean,
      'initialAdminPrincipal' : Principal,
      'callerPrincipal' : Principal,
    }
  >,
  'getAllComplaints' : ActorMethod<[], Array<Complaint>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplaint' : ActorMethod<[bigint], [] | [Complaint]>,
  'getCurrentUserPrincipal' : ActorMethod<[], CallerInfo>,
  'getPublicComplaints' : ActorMethod<[], Array<Complaint>>,
  'getSolutions' : ActorMethod<[], Array<SolutionUpdate>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hideComplaint' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchComplaints' : ActorMethod<[string], Array<Complaint>>,
  'submitComplaint' : ActorMethod<
    [ComplaintCategory, string, string, [] | [ExternalBlob]],
    bigint
  >,
  'updateComplaintStatus' : ActorMethod<[bigint, ComplaintStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];